### PR TITLE
Creating a pull request for adding RADICaL model in NeuroCAAS platform

### PR DESCRIPTION
**Pull request by anjaliagarwal8**
RADICaL model can help users in estimating network states and dynamics from 2-photon (2p) calcium imaging measurements.

### CODE REVIEW

**Comment by cellistigs** [comment]
Hi Anjali, thanks for this PR, it looks great. I'm going to run tests against it and we can get started. Do you already have a user account on the NeuroCAAS website? If so, I can upgrade that to developer status.

**Comment by anjaliagarwal8** [comment]
Hi @cellistigs Thank you. 
We didn't have a user account on NeuroCAAS website but we have created one and will send you the info as soon as it is reviewed.

**Comment by cellistigs** [comment]
#deploy:radical

**Comment by cellistigs** [comment]
#deploy:radical

**Comment by cellistigs** [comment]
#deploy:radical

**Comment by cellistigs** [comment]
#deploy:radical

**Comment by cellistigs** [comment]
#deploy:radical

**Comment by cellistigs** [comment]
#deploy:radical

**Comment by cellistigs** [comment]
#deploy:radical

**Comment by cellistigs** [comment]
#deploy:radical

**Pull request merged**
