### PR TITLE
Labeljobcreate

### PR DESCRIPTION
**Pull request by nickgreenspan**
Added blueprint for labeljobcreate

### CODE REVIEW

**Comment by cellistigs** [comment]
Testing deployment on this branch.

**Comment by cellistigs** [comment]
#deploy:labeljobcreate

**Comment by cellistigs** [comment]
Got name wrong, redeploying

**Comment by cellistigs** [comment]
#deploy:label-job-create

**Comment by cellistigs** [comment]
Error- blueprint fields missing. pulling and redeploying.

**Comment by cellistigs** [comment]
#deploy:label-job-create

**Comment by cellistigs** [comment]
Bucket named label-job-create already exists. Try again with label-job-create-web

**Comment by cellistigs** [comment]
#deploy:label-job-create

**Comment by cellistigs** [comment]
-Updated AMI with a conda environment, "label". This is necessary because SSM running jobs remotely does not access the same python as the user (fix this later). 
-Updated paths for command to be absolute paths, and run from the root directory. 
-Created a new EC2 Instance Profile exclusively for this job: SagemakerRole.

**Comment by cellistigs** [comment]
Looks like label jobs can launch now. Deploying latest version.

**Comment by cellistigs** [comment]
#deploy:label-job-create

**Comment by cellistigs** [comment]
Deploying with new user group added to see if we can nail down this bug.

**Comment by cellistigs** [comment]
#deploy:label-job-create

**Comment by cellistigs** [comment]
Fake user was part of too many groups, removing and just creating group.

**Comment by cellistigs** [comment]
#deploy:label-job-create

**Comment by cellistigs** [comment]
#deploy:label-job-create

**Comment by cellistigs** [comment]
messed up suffix for testing name.

**Comment by cellistigs** [comment]
#deploy:label-job-create

**Comment by cellistigs** [comment]
added testgroup6 to match what has worked before.

**Comment by cellistigs** [comment]
#deploy:label-job-create

**Comment by cellistigs** [comment]
#deploy:label-job-create

**Comment by cellistigs** [comment]
We need a way to specify alternative requirements files before we can merge this stack. Otherwise the pandas requirements will not be met.

**Comment by nickgreenspan** [comment]
- Added functionality for zipped folders of frames as input data for labeling job. If you want use this functionality you should set the "dataformat" field of the labeling config file to "frames", otherwise if you want to submit a video and extract the first x  number of frames (where you specify x in the config file) you should set the field equal to "video". You should submit a zip file of a folder which contains frames to be labeled which are named in the following manner: 
begin + num + extension (don’t include the pluses in the actual filename)
Where begin is a non-numeric string of text with no special characters (can be excluded), num is a number that specifies the order you want the frames to be labeled in, and extension is .jpeg, .png, or .jpg
- Changed file path structure in final bucket to include job name so multiple jobs can use the same final bucket.

**Comment by cellistigs** [comment]
#deploy:label-job-create

**Comment by cellistigs** [comment]
Remaining big todos: 
- Have different folders be sucked into different labeling jobs. This could let you farm out different jobs to different users. 
- More sophisticated frame selection when working directly from a video (motion energy, k means). 
- decrease instance size when running from frames so we use less $$

**Comment by cellistigs** [comment]
#deploy:label-job-create

**Comment by cellistigs** [comment]
#deploy:label-job-create

**Comment by cellistigs** [comment]
#deploy:label-job-create

**Pull request merged**
