### PR TITLE
Adding AutoLFADS to NeuroCAAS

### PR DESCRIPTION
**Pull request by arsedler9**
We've developed a more modular and extensible version of [AutoLFADS](https://www.nature.com/articles/s41592-022-01675-0) using modern frameworks like PyTorch, PyTorch Lightning, Hydra, Ray Tune that we would like to make available on NeuroCAAS.

### CODE REVIEW

**Comment by arsedler9** [comment]
Hey @cellistigs do you have a way for me to create a NeuroCAAS S3 bucket to test the workflow with my current image?

**Comment by cellistigs** [comment]
Hey Andrew! One will be created automatically when you are ready to deploy your analysis blueprint for the first time (that doesn't open it to anybody, it's just a development step). If you feel you need to take some more time beforehands we can certainly create a temporary bucket too.

**Comment by arsedler9** [comment]
Got it, thanks. I think we should be ready to deploy!

**Comment by arsedler9** [comment]
@cellistigs is there anything I need to do on my side to deploy?

**Comment by cellistigs** [comment]
Sorry for the delay Andrew! I'll deploy now.

**Comment by cellistigs** [comment]
#deploy:autolfads-torch

**Comment by cellistigs** [comment]
Apologies, I'm running into some issues with the deployment setup. I will resolve these and notify you as soon as deployment is complete.

**Comment by cellistigs** [comment]
#deploy:autolfads-torch

**Comment by cellistigs** [comment]
Hey @arsedler9, I made some edits to your fork (shown above), and was able to deploy your analysis. There should now be a bucket called autolfads-torch which you can use to further test your analyses.

**Comment by arsedler9** [comment]
Thanks @cellistigs, I just pulled down your changes to start testing and am running into some issues that you might be able to help with. To start testing, I first uploaded my test config and dataset to the S3 bucket:
```
aws s3 cp /path/to/pbt_mc_maze-20ms-val.yaml s3://autolfads-torch/systemsneura1639759179/configs/pbt_mc_maze-20ms-val.yaml
aws s3 cp /path/to/mc_maze-20ms-val.h5 s3://autolfads-torch/systemsneura1639759179/inputs/mc_maze-20ms-val.h5
```
I then started a session, launched an instance based on the AMI I had been using, and tried to submit a job:
```
neurocaas-contrib remote start-session
neurocaas-contrib remote launch-devinstance -a "ami-0729721d91fcfdcd5" -v 128 -t 180
neurocaas-contrib remote submit-job -s neurocaas_submissions/submit.json
```
The contents of `neurocaas_submissions/submit.json` was the following:
```
{
    "dataname": "systemsneura1639759179/inputs/mc_maze-20ms-val.h5",
    "configname": "systemsneura1639759179/configs/pbt_mc_maze-20ms-val.yaml",
    "timestamp": "debugging_identifier"
}
```
The first time I tried this, I got an error regarding a missing `SSM_TIMEOUT` key on the `LambdaConfig`. Based on other blueprints, I added `SSM_TIMEOUT` and `EXECUTION_TIMEOUT` keys. After fixing that issue, I was getting `AccessDenied` so I tried updating the `COMMAND` with `sudo -u ubuntu` as noted in the docs. This didn't fix `AccessDenied`, so I took a closer look at `COMMAND` and realized the paths might have been out of date (`neurocaas_remote` vs `neurocaas_contrib`). Fixed this issue and I'm still getting `AccessDenied`. Do you have any insight as to what might be going wrong here?

Here is the current blueprint I'm using:
```
{
    "PipelineName": "autolfads-torch",
    "REGION": "us-east-1",
    "STAGE": "webdev",
    "Lambda": {
        "CodeUri": "../../protocols",
        "Handler": "submit_start.handler_develop",
        "Launch": true,
        "LambdaConfig": {
            "AMI": "ami-0729721d91fcfdcd5",
            "INSTANCE_TYPE": "p2.8xlarge",
            "REGION": "us-east-1",
            "IAM_ROLE": "SSMRole",
            "KEY_NAME": "testkeystack-custom-dev-key-pair",
            "WORKING_DIRECTORY": "~/bin",
            "COMMAND": "cd /home/ubuntu; sudo -u ubuntu neurocaas_contrib/run_main.sh \"{}\" \"{}\" \"{}\" \"{}\"; . neurocaas_contrib/ncap_utils/workflow.sh; cleanup",
            "EXECUTION_TIMEOUT": 900,
            "SSM_TIMEOUT": 172000
        }
    },
    "UXData": {
        "Affiliates": [
            {
                "AffiliateName": "traviscipermagroup",
                "UserNames": [
                    "cipermauser1",
                    "cipermauser2"
                ],
                "UserInput": true,
                "ContactEmail": "NOTE: KEEP THIS AFFILIATE TO ENABLE EASY TESTING"
            },
            {
                "AffiliateName": "systemsneura1639759179",
                "UserNames": [
                    "systemsneura1639759178"
                ],
                "UserInput": true,
                "ContactEmail": "NOTE: KEEP THIS AFFILIATE TO ENABLE EASY TESTING"
            }
        ]
    }
}
```
And here is the resulting error message:
```
(neurocaas) arsedle@nimbus:~$ neurocaas-contrib remote submit-job -s neurocaas_submissions/submit.json
/home/arsedle/miniconda3/envs/neurocaas/lib/python3.6/site-packages/paramiko/transport.py:33: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography. The next release of cryptography will remove support for Python 3.6.
  from cryptography.hazmat.backends import default_backend
/home/arsedle/miniconda3/envs/neurocaas/lib/python3.6/site-packages/paramiko/transport.py:219: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
Instance i-0c7fa5776202975de exists and is active, safe to test
sending command: cd /home/ubuntu; sudo -u ubuntu neurocaas_contrib/run_main.sh "autolfads-torch" "systemsneura1639759179/inputs/mc_maze-20ms-val.h5" "results/debugjob2023-05-23 15:56:19.849541" "systemsneura1639759179/configs/pbt_mc_maze-20ms-val.yaml"; . neurocaas_contrib/ncap_utils/workflow.sh; cleanup to instance i-0c7fa5776202975de
Traceback (most recent call last):
  File "/home/arsedle/miniconda3/envs/neurocaas/bin/neurocaas-contrib", line 33, in <module>
    sys.exit(load_entry_point('neurocaas-contrib', 'console_scripts', 'neurocaas-contrib')())
  File "/home/arsedle/neurocaas_contrib/src/neurocaas_contrib/main.py", line 5, in main
    cli()
  File "/home/arsedle/miniconda3/envs/neurocaas/lib/python3.6/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/arsedle/miniconda3/envs/neurocaas/lib/python3.6/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/arsedle/miniconda3/envs/neurocaas/lib/python3.6/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/arsedle/miniconda3/envs/neurocaas/lib/python3.6/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/arsedle/miniconda3/envs/neurocaas/lib/python3.6/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/arsedle/miniconda3/envs/neurocaas/lib/python3.6/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/arsedle/miniconda3/envs/neurocaas/lib/python3.6/site-packages/click/decorators.py", line 38, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/arsedle/neurocaas_contrib/src/neurocaas_contrib/cli_commands.py", line 1554, in submit_job
    ami.submit_job(submitpath)
  File "/home/arsedle/neurocaas_contrib/src/neurocaas_contrib/remote.py", line 378, in submit_job
    statusobj.put(Body = (bytes(json.dumps(template_dict).encode("UTF-8"))))
  File "/home/arsedle/miniconda3/envs/neurocaas/lib/python3.6/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/home/arsedle/miniconda3/envs/neurocaas/lib/python3.6/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/home/arsedle/miniconda3/envs/neurocaas/lib/python3.6/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/arsedle/miniconda3/envs/neurocaas/lib/python3.6/site-packages/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the PutObject operation: Access Denied
```

**Comment by cellistigs** [comment]
Thanks @arsedler9 for the very thorough debugging! This is an issue with the initial job submission and I'll have to take a look at the permissions assigned to you. I'll have an answer for you by tomorrow!

**Comment by cellistigs** [comment]
Hi @arsedler9, would you mind please running the following for me: 

`aws s3 cp neurocaas_submissions/submit.json s3://autolfads-torch/systemsneura1639759179/submissions/submit.json`

This is the portion of the `submit-job` command that I suspect is returning the permissions error you are running into. 

Thank you!

**Comment by arsedler9** [comment]
Thanks for the quick response! I just ran that command by itself and it seems to have worked:
```
(neurocaas) arsedle@nimbus:~$ aws s3 cp neurocaas_submissions/submit.json s3://autolfads-torch/systemsneura1639759179/submissions/submit.json
upload: neurocaas_submissions/submit.json to s3://autolfads-torch/systemsneura1639759179/submissions/submit.json
(neurocaas) arsedle@nimbus:~$ aws s3 ls s3://autolfads-torch/systemsneura1639759179/submissions/
2023-05-05 12:13:31          0
2023-05-25 18:28:11        191 submit.json
```

**Comment by cellistigs** [comment]
Awesome, thanks! I've implemented some edits that I hope will fix your issue, would you mind running the `submit-job` command again? Very much appreciated.

**Comment by arsedler9** [comment]
Just tried running the same commands I from the other day and unfortunately got the same error:
```
neurocaas-contrib remote start-session
neurocaas-contrib remote launch-devinstance -a "ami-0729721d91fcfdcd5" -v 128 -t 180
neurocaas-contrib remote submit-job -s neurocaas_submissions/submit.json
```

**Comment by arsedler9** [comment]
Got a new error when I tried to end the session, though:
```
(neurocaas) arsedle@nimbus:~$ neurocaas-contrib remote end-session -f
/home/arsedle/miniconda3/envs/neurocaas/lib/python3.6/site-packages/paramiko/transport.py:33: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography. The next release of cryptography will remove support for Python 3.6.
  from cryptography.hazmat.backends import default_backend
/home/arsedle/miniconda3/envs/neurocaas/lib/python3.6/site-packages/paramiko/transport.py:219: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
Detected an existing development session with instance i-0cb9f4d693a2846c9 for analysis autolfads-torch. Delete session? [y/N]: y
Instance i-0cb9f4d693a2846c9 is terminating
Traceback (most recent call last):
  File "/home/arsedle/miniconda3/envs/neurocaas/bin/neurocaas-contrib", line 33, in <module>
    sys.exit(load_entry_point('neurocaas-contrib', 'console_scripts', 'neurocaas-contrib')())
  File "/home/arsedle/neurocaas_contrib/src/neurocaas_contrib/main.py", line 5, in main
    cli()
  File "/home/arsedle/miniconda3/envs/neurocaas/lib/python3.6/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/arsedle/miniconda3/envs/neurocaas/lib/python3.6/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/arsedle/miniconda3/envs/neurocaas/lib/python3.6/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/arsedle/miniconda3/envs/neurocaas/lib/python3.6/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/arsedle/miniconda3/envs/neurocaas/lib/python3.6/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/arsedle/miniconda3/envs/neurocaas/lib/python3.6/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/arsedle/miniconda3/envs/neurocaas/lib/python3.6/site-packages/click/decorators.py", line 38, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/arsedle/neurocaas_contrib/src/neurocaas_contrib/cli_commands.py", line 1384, in end_session
    deleted = delete_ami_from_cli(dev_dict,force)
  File "/home/arsedle/neurocaas_contrib/src/neurocaas_contrib/cli_commands.py", line 68, in delete_ami_from_cli
    message = ami.terminate_devinstance(force)
  File "/home/arsedle/neurocaas_contrib/src/neurocaas_contrib/remote.py", line 502, in terminate_devinstance
    waiter.wait(InstanceIds = [self.instance.instance_id])
  File "/home/arsedle/miniconda3/envs/neurocaas/lib/python3.6/site-packages/botocore/waiter.py", line 53, in wait
    Waiter.wait(self, **kwargs)
  File "/home/arsedle/miniconda3/envs/neurocaas/lib/python3.6/site-packages/botocore/waiter.py", line 353, in wait
    last_response=response,
botocore.exceptions.WaiterError: Waiter InstanceTerminated failed: Waiter encountered a terminal failure state: For expression "Reservations[].Instances[].State.Name" we matched expected path: "stopping" at least once
```

**Comment by cellistigs** [comment]
Sorry about that- there was a typo in the permissions file. It should be set now! 

Regarding that last error, it looks like there was some sort of race that happened, where the instance tried to stop and terminate at the same time. It should not be an issue with launching successive deployments, but I will open an issue about it. Thank you!

**Comment by arsedler9** [comment]
Now it seems to have gone through with no error, but there's no output in the bucket and the instance shut down right away. I'll try taking a closer look to see if I missed anything in the code or docs.
```
(neurocaas) arsedle@nimbus:~$ neurocaas-contrib remote submit-job -s neurocaas_submissions/submit.json
/home/arsedle/miniconda3/envs/neurocaas/lib/python3.6/site-packages/paramiko/transport.py:33: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography. The next release of cryptography will remove support for Python 3.6.
  from cryptography.hazmat.backends import default_backend
/home/arsedle/miniconda3/envs/neurocaas/lib/python3.6/site-packages/paramiko/transport.py:219: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
Instance i-081ff36d9becdf6f3 exists and is active, safe to test
sending command: cd /home/ubuntu; sudo -u ubuntu neurocaas_contrib/run_main.sh "autolfads-torch" "systemsneura1639759179/inputs/mc_maze-20ms-val.h5" "results/debugjob2023-05-26 15:52:36.969828" "systemsneura1639759179/configs/pbt_mc_maze-20ms-val.yaml"; . neurocaas_contrib/ncap_utils/workflow.sh; cleanup to instance i-081ff36d9becdf6f3
```

**Comment by cellistigs** [comment]
Glad to hear that error is solved! You can temporarily remove the option for the instance to auto-stop by removing the `cleanup` call from the `COMMAND` field (I.e. the command would then be `cd /home/ubuntu; sudo -u ubuntu neurocaas_contrib/run_main.sh \"{}\" \"{}\" \"{}\" \"{}\"; . neurocaas_contrib/ncap_utils/workflow.sh"`). 

If it becomes difficult to determine the source of the error, please let me know and I can provide more debugging tools as useful.

**Comment by arsedler9** [comment]
I think I figured out the error. Rather than using `run_main.sh` in `COMMAND` as was generated automatically, it looks like I should be using `run_main_cli.sh`. One problem with that is that the blueprint is set up to pass 4 arguments to the main script but `run_main_cli.sh` requires 5 (new arg needed to tell `log-command` where the analysis script is). I'm a bit confused about where these `{}` arguments are filled in and whether / how NeuroCAAS is set up to pass that info. Presumably there's a new field I need to add to the `submit.json` and another `{}` I need to add to the blueprint?

**Comment by cellistigs** [comment]
#deploy:autolfads

**Comment by cellistigs** [comment]
Mistake in name- redeploying.

**Comment by cellistigs** [comment]
#deploy:autolfads-torch

**Comment by cellistigs** [comment]
Deployment looks to have succeeded. There should now be an S3 bucket called autolfads-torch, with folders for individual users that can be used to launch analyses.

**Comment by cellistigs** [comment]
Had to update `STAGE` from `webdev` to `websubstack` for testing.

**Comment by cellistigs** [comment]
#deploy:autolfads-torch

**Comment by cellistigs** [comment]
#deploy:autolfads-torch

**Comment by cellistigs** [comment]
#deploy:autolfads-torch

**Comment by cellistigs** [comment]
#deploy:autolfads-torch

**Pull request closed without merging**
